[package]
edition = '2021'
name = "flac-tracksplit"
version = "0.0.1-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
repository = "https://github.com/antifuchs/flac-tracksplit"
readme = "README.md"
description = "Split FLAC+CUE (embedded) into multiple tracks"
documentation = "https://docs.rs/flac-tracksplit"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
symphonia-bundle-flac = { git = "https://github.com/antifuchs/Symphonia.git", branch = "debug-trait" }
symphonia-core = { git = "https://github.com/antifuchs/Symphonia.git", branch = "debug-trait" }
symphonia-utils-xiph = { git = "https://github.com/antifuchs/Symphonia.git", branch = "debug-trait" }
