[package]
edition = '2021'
name = "flac-tracksplit"
version = "0.0.1-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
repository = "https://github.com/antifuchs/flac-tracksplit"
readme = "README.md"
description = "Split FLAC+CUE (embedded) into multiple tracks"
documentation = "https://docs.rs/flac-tracksplit"

[[bin]]
name = "flac-tracksplit"
path = "src/main.rs"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
anyhow = "1.0.52"
clap = { version = "4.2.7", features = ["derive"] }
crc = "2.1.0"
int-conv = "0.1.4"
metaflac = "0.2.5"
more-asserts = "0.3.1"
rayon = "1.7.0"
symphonia-bundle-flac = "0.5.2"
symphonia-core = "0.5.2"
symphonia-utils-xiph = "0.5.2"
tracing = "0.1.37"
tracing-indicatif = "0.3.4"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
proptest = "1.1.0"
